name: Tests

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: psf/black@stable
      - name: Flake8
        run: |
          python -m pip install flake8
          flake8 . --max-line-length=88 --extend-exclude="migrations,tests.py" --count --statistics
      - name: mypy
        run: |
          python -m pip install mypy
          mypy . --ignore-missing-imports --exclude migrations/ --exclude tests
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        django-version: ["4.2", "5.0", "5.1"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install Django~=${{ matrix.django-version }}
      - name: Run Tests
        run: |
          django-admin startproject example .
          echo "INSTALLED_APPS.append('django_html_utils')" >> example/settings.py
          python manage.py test
